"""Add source column to attachments table

Revision ID: 0004
Revises: 7e585de6e9c2
Create Date: 2025-10-16 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '7e585de6e9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('source', sa.String(length=50), nullable=False, server_default='upload'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'source')
    # ### end Alembic commands ###
