"""add_full_name_to_user

Revision ID: 7e585de6e9c2
Revises: 0003_add_enrollment_chapter_attachment_live_class_models
Create Date: 2025-10-15 10:48:53.881965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e585de6e9c2'
down_revision: Union[str, None] = '0003_add_enrollment_chapter_attachment_live_class_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
